import { v4 as uuidv4 } from "uuid";

export const procuctsDatabase = [
  {
    id: uuidv4(),
    img: "/imagesProducts/Cama.png",
    nameItem: "Cama",
    description:
      "Espuma resistente sem abrir mão do conforto que seu pet merece.",
    value: 110,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/racaoSecaParaCaes.png",
    nameItem: "Ração seca para cães - 3 kg",
    description: "Com todas as vitaminas e minerais que seu cãozinho precisa.",
    value: 150,
    addCart: "Adicionar ao carrinho",
    tag: ["Alimentação"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/Coleira.png",
    nameItem: "Coleira auto ajustável",
    description: "Como ela se ajusta em todos os pescoços é um mistério.",
    value: 40,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/racaoUmidaParaGatos.png",
    nameItem: "Ração úmida para gatos 150 g",
    description: "Com todas as vitaminas que seu gatinho precisa.",
    value: 10,
    addCart: "Adicionar ao carrinho",
    tag: ["Alimentação"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/torreParaGatos.png",
    nameItem: "Torre para gatos",
    description: "Resistente e durável. Acolchoamento interno premium.",
    value: 230,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/biscoitoParaCaes.png",
    nameItem: "Biscoito para Cães - 200 g",
    description: "Ingredientes naturais e orgânicos. Rico em fibras.",
    value: 15,
    addCart: "Adicionar ao carrinho",
    tag: ["Alimentação"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/cortadorDeUnhas.png",
    nameItem: "Cortador de unhas",
    description: "Com trava! Mais segurança para aparar as unhas do seu pet.",
    value: 38,
    addCart: "Adicionar ao carrinho",
    tag: ["Higiene"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/toca.png",
    nameItem: "Toca",
    description: "Quentinha e confortável, seu pet vai amar!",
    value: 210,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/brinquedoCordinha.png",
    nameItem: "Brinquedo de cordinha para cães",
    description: "Diversão garantida! Nosso campeão de vendas em acessórios.",
    value: 13,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/Comedouro.png",
    nameItem: "Comedouro / Bebedouro",
    description: "Em cerâmica. Mantém a água fresca nos dias quentes.",
    value: 35,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/Escova.png",
    nameItem: "Escova",
    description: "Técnologia que deixa o pelinho do seu pet mais macio.",
    value: 23,
    addCart: "Adicionar ao carrinho",
    tag: ["Higiene"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/caixaDeTransporte.png",
    nameItem: "Caixa de transporte",
    description: "Mais conforto e segurança ao transportar seu pet.",
    value: 159,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/saquinhosHigienicos.png",
    nameItem: "Saquinhos higiênicos com dispenser",
    description:
      "Mais praticidade na hora de levar seu pet para aquele passeio.",
    value: 29,
    addCart: "Adicionar ao carrinho",
    tag: ["Higiene"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/Pente.png",
    nameItem: "Pente",
    description: "Desembarace com facilidade o pelo do seu pet.",
    value: 24,
    addCart: "Adicionar ao carrinho",
    tag: ["Higiene"],
  },
  {
    id: uuidv4(),
    img: "/imagesProducts/Casinha.png",
    nameItem: "Casa",
    description:
      "Técnologia que mantém a temperatura interna ideal para o seu pet.",
    value: 260,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
];
